package org.whisperim.client;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.*;

import java.util.HashMap;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WhisperClient.java
 *
 * Created on Dec 5, 2008, 3:13:05 PM
 */

/**
 *
 * @author Kirk Banks, Chris Thompson
 */
public class WhisperClient extends javax.swing.JFrame {

    private String[] buddyString;
    private int numOfBuddies = 0;
    private String myHandle_;
    private Timer myTimer;
    private IdleTT myTaskTimer;
        
    private ConnectionManager manager_;

    private HashMap<String, WhisperIM> windows = new HashMap<String, WhisperIM>();
    /** Creates new form WhisperClient */
    public WhisperClient(String handle, ConnectionManager manager) {
        initComponents();
        manager_ = manager;
        manager_.setClient(this);
        myHandle_ = handle;
        this.setTitle("Whisper");
        
        myTimer = new Timer();
        myTaskTimer = new IdleTT();
        myTimer.schedule(myTaskTimer, 5000); //user goes idle after 5 seconds for demo/test purposes    
    }
    
    class IdleTT extends TimerTask {
        public void run() {
        	setTitle("Whisper [Idle]");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        Buddies = new java.awt.List();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        popupMenu1.setLabel("popupMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Buddies.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BuddiesComponentShown(evt);
            }
        });
        Buddies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuddiesActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem2.setText("Quit");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Preferences");

        jMenuItem1.setText("Encryption");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Buddies, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(Buddies, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuddiesActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuddiesActionPerformed
        //Create IM window
    	final WhisperClient client = this;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WhisperIM window = new WhisperIM(evt.getActionCommand(), myHandle_, client, manager_.getPrivateKey());
                window.setVisible(true);
                windows.put(evt.getActionCommand(), window);
            }
        });
}//GEN-LAST:event_BuddiesActionPerformed

    private void BuddiesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BuddiesComponentShown


    }//GEN-LAST:event_BuddiesComponentShown

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        manager_.signOff();
    }//GEN-LAST:event_formWindowClosing
    
    public void recieveMessage(final Message message){
    	if (windows.get(message.getFrom()) == null){
    		//There isn't currently a window associated with that buddy
    		final WhisperClient client = this;
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    WhisperIM window = new WhisperIM(message.getFrom(), myHandle_, client, manager_.getPrivateKey());
                    window.setVisible(true);
                    windows.put(message.getFrom(), window);
                    windows.get(message.getFrom()).receiveMsg(message);
                }
            });
            
    	}else{
    		windows.get(message.getFrom()).receiveMsg(message);
    	}
    	


    }

    public void sendMessage (Message message){
        manager_.sendMessage(message);
        
        this.setTitle("Whisper");
        
        myTaskTimer.cancel();
        myTaskTimer = new IdleTT();
        myTimer.schedule(myTaskTimer, 5000);
    }


    public void updateBuddyList(ArrayList<String> newBuddies)
    {
        numOfBuddies = newBuddies.size();
        
        for(int i=0; i<newBuddies.size(); i++)
        {
           Buddies.add(newBuddies.get(i));
        }
        
    }
    
    public void onWindowClose(String handle){
    	windows.remove(handle);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List Buddies;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables

}
