 /**************************************************************************
 * Copyright 2009 John Dlugokecki                                         *
 *                                                                         *
 * Licensed under the Apache License, Version 2.0 (the "License");         *
 * you may not use this file except in compliance with the License.        *
 * You may obtain a copy of the License at                                 *
 *                                                                         *
 * http://www.apache.org/licenses/LICENSE-2.0                              *
 *                                                                         *
 * Unless required by applicable law or agreed to in writing, software     *
 * distributed under the License is distributed on an "AS IS" BASIS,       *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*
 * See the License for the specific language governing permissions and     *
 * limitations under the License.                                          *
 **************************************************************************/
package org.whisperim.client;
import javax.swing.*;

import org.whisperim.security.Encryptor;

import java.security.PrivateKey;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 * The majority of this class is auto-generated code using Java's swing UI
 * components. The primary method of interest is the WhisperIM constructor that
 * is called from WhisperClient.java
 * 
 * @author Kirk Banks, Chris Thompson, John Dlugokecki
 */
public class WhisperIM extends javax.swing.JFrame{
    //Encryptor for the chat session
    private Encryptor encrypt;
    private boolean doEncryption = false;
    private String theirHandle_;
    private String myHandle_;
    private WhisperClient myParent_;
  
    
    /** Creates new form WhisperIM */
    public WhisperIM(String theirHandle, String myHandle, WhisperClient myParent, PrivateKey myKey) {
    	super("Whisper IM Conversation with " + theirHandle);
    	initComponents();
        buddyName_.setText(theirHandle);
        encrypt = new Encryptor(Encryptor.getPublicKeyForBuddy(theirHandle), myKey);
        toggleEncryption_.setSelected(doEncryption);
        toggleEncryption_.setText("Encryption: Off");
        talkArea_.requestFocus();
        theirHandle_ = theirHandle;
        myHandle_ = myHandle;
        myParent_ = myParent;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1_ = new javax.swing.JDialog();
        jDialog2_ = new javax.swing.JDialog();
        messageArea_ = new java.awt.TextArea();
        sendBtn_ = new javax.swing.JButton();
        jScrollPane1_ = new javax.swing.JScrollPane();
        talkArea_ = new javax.swing.JTextArea();
        buddyName_ = new javax.swing.JLabel();
        toggleEncryption_ = new javax.swing.JToggleButton();

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1_.getContentPane());
        jDialog1_.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jDialog2Layout = new org.jdesktop.layout.GroupLayout(jDialog2_.getContentPane());
        jDialog2_.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 315));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        sendBtn_.setText("Send");
        sendBtn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        talkArea_.setColumns(20);
        talkArea_.setRows(5);
        jScrollPane1_.setViewportView(talkArea_);

        buddyName_.setText("jLabel1");

        toggleEncryption_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleEncryptionActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(buddyName_, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 200, Short.MAX_VALUE)
                        .add(toggleEncryption_))
                    .add(jScrollPane1_, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .add(messageArea_, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .add(sendBtn_))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(buddyName_, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(toggleEncryption_))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1_, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(messageArea_, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sendBtn_)
                .add(42, 42, 42))
        );

        buddyName_.getAccessibleContext().setAccessibleName("Buddy");
    }// </editor-fold>//GEN-END:initComponents

    private void toggleEncryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleEncryptionActionPerformed
        if (doEncryption){
            doEncryption = false;
            toggleEncryption_.setText("Encryption: Off");
        }else{
            doEncryption = true;
            toggleEncryption_.setText("Encryption: On");
        }
}//GEN-LAST:event_toggleEncryptionActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        
    	if (messageArea_.getText().equalsIgnoreCase(""))
    	{
    		//Message area is empty, do nothing
    	}else{
    		sendMsg();
    	}
    	
}//GEN-LAST:event_sendBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    	System.out.println("Window closing");
    	myParent_.onWindowClose(theirHandle_);
    }//GEN-LAST:event_formWindowClosing

    public void receiveMsg(Message message)
    {
    	
    	
    	DateFormat d = DateFormat.getTimeInstance(DateFormat.MEDIUM);
    	talkArea_.append("(" + d.format(message.getTimeSent()) + ") ");
    	talkArea_.append(message.getFrom() + ": ");
        
    	if (!doEncryption || !message.getMessage().contains("<key>")){
    		talkArea_.append(message.getMessage());
    	}else{
    		
    		talkArea_.append("(Encrypted Message) " + encrypt.decryptMessage(message.getMessage()));
    	}
        
        talkArea_.append("\n");
    }

    public void sendMsg()
    {
        //Code needed for sending
        String messageText;
        Calendar now = Calendar.getInstance();
        Date d = now.getTime();
        DateFormat df1 = DateFormat.getTimeInstance(DateFormat.MEDIUM);
        if (doEncryption){
            //Message will be encrypted
        	talkArea_.append("(" + df1.format(d) + ") " + myHandle_ + ":  (Ecrypted Message) " + messageArea_.getText() + "\n");
            messageText = encrypt.generateCipherText(messageArea_.getText());
        }else{
        	talkArea_.append("(" + df1.format(d) + ") " + myHandle_ + ": " + messageArea_.getText() + "\n");
            messageText = messageArea_.getText();
        }

        Message message = new Message(myHandle_, theirHandle_, messageText, Calendar.getInstance().getTime());
        
        myParent_.sendMessage(message);
        messageArea_.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buddyName_;
    private javax.swing.JDialog jDialog1_;
    private javax.swing.JDialog jDialog2_;
    private javax.swing.JScrollPane jScrollPane1_;
    private java.awt.TextArea messageArea_;
    private javax.swing.JButton sendBtn_;
    private javax.swing.JTextArea talkArea_;
    private javax.swing.JToggleButton toggleEncryption_;
    // End of variables declaration//GEN-END:variables

}
